### ISSUE TITLE
what is this nonsense

### ISSUE THREAD

**Issue by astrobdr** [CalamariDude/youtube#1]
boi 👏

**Comment by shatz01** [comment]
👀

**Comment by shatz01** [comment]
🅱️

**Comment by shatz01** [comment]
👀

**Comment by shatz01** [comment]
👀
👀👀
👀👀👀
👀👀👀👀
👀👀👀👀👀
👀👀👀👀👀👀                     👀
👀👀👀👀👀
👀👀👀👀
👀👀👀
👀👀
👀

**Comment by shatz01** [comment]
🍑

**Comment by shatz01** [comment]
🍳

**Comment by CalamariDude** [comment]
Looking into it, have you tried running
`npm install toshiba-tiktok-xaomi`

**Comment by shatz01** [comment]
> tiktok-xaomi

do i look like chinese-software-running-communist-filth TO U? 😤

plz dnt hurt mi big dady trumpf

**Comment by CalamariDude** [comment]
that fixed my problem thank you

**Comment by shatz01** [comment]
THIS IS NOT OVER.
